### ISSUE TITLE
The Spatial attention module code

### ISSUE THREAD

**Issue by torchmyheart** [Christian-lyc/NAM#2]
Hello, thank you very much for your great work. But your code seems don't  include  the Spatial attention module. Can this part of the code be open sourced? Thanks again and look forward to your reply!

**Comment by Christian-lyc** [comment]
Hi, thank you for your interest. Please see the closed issue.
Best regards,

**Comment by torchmyheart** [comment]
Hi, thank you very much for your quick reply. And I still have a few questions. Is the location of the Spatial attention module the same as that of the Channel attention module?  When using two modules at the same time, what order is better? Thanks again and look forward to your reply!

**Comment by Christian-lyc** [comment]
If you see the CBAM structure, in general, the channel attention is before the spatial attention.







--

Mit einem Lachen auf den Lippen wird vieles einfacher.

LYC




在 2021-12-05 13:28:59，"coderrubbish" ***@***.***> 写道：

Hi, thank you very much for your quick reply. And I still have a few questions. Is the location of the Spatial attention module the same as that of the Channel attention module? When using two modules at the same time, what order is better? Thanks again and look forward to your reply!

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Ronky123** [comment]
> Hi, thank you very much for your quick reply. And I still have a few questions. Is the location of the Spatial attention module the same as that of the Channel attention module? When using two modules at the same time, what order is better? Thanks again and look forward to your reply!

Hi,do you implement the Saptial attention about the NAM?Could we have a talking?
